
DROP DATABASE IF EXISTS sistema_transporte;

CREATE DATABASE sistema_transporte
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE sistema_transporte;

CREATE TABLE SERVICIO (
    ID_SERVICIO   INT           NOT NULL AUTO_INCREMENT,
    TIPO_S        VARCHAR(50)   NOT NULL,
    BLOQUEO_DE_T  TINYINT(1)    NOT NULL DEFAULT 0,  -- 0=activo, 1=bloqueado
    PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE CANAL (
    ID_CANAL   INT          NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_CANAL)
);


CREATE TABLE PUNTO_AUTORIZADO (
    ID_LOCAL   INT          NOT NULL AUTO_INCREMENT,
    DIRECCION  VARCHAR(200) NOT NULL,
    ID_CANAL   INT          NOT NULL,
    PRIMARY KEY (ID_LOCAL),
    CONSTRAINT fk_pa_canal FOREIGN KEY (ID_CANAL) REFERENCES CANAL(ID_CANAL)
);

CREATE TABLE APLICACION_OFICIAL (
    ID_APP     INT          NOT NULL AUTO_INCREMENT,
    ID_CANAL   INT          NOT NULL,
    PRIMARY KEY (ID_APP),
    CONSTRAINT fk_app_canal FOREIGN KEY (ID_CANAL) REFERENCES CANAL(ID_CANAL)
);

CREATE TABLE RECARGA (
    ID_RECARGA   INT            NOT NULL AUTO_INCREMENT,
    MONTO        DECIMAL(10,2)  NOT NULL,
    TIPO_DE_PAGO VARCHAR(50)    NOT NULL,
    ID_CANAL     INT            NOT NULL,
    PRIMARY KEY (ID_RECARGA),
    CONSTRAINT fk_rec_canal FOREIGN KEY (ID_CANAL) REFERENCES CANAL(ID_CANAL)
);

CREATE TABLE USUARIO (
    ID_USUARIO  INT          NOT NULL AUTO_INCREMENT,
    NOMBRE      VARCHAR(100) NOT NULL,
    CONTRASENA  VARCHAR(255) NOT NULL,
    CORREO      VARCHAR(100) NOT NULL UNIQUE,
    NUMERO_TEL  VARCHAR(20),
    DIRECCION   VARCHAR(200),
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO    INT NOT NULL,
    PRIMARY KEY (ID_ESTUDIANTE),
    CONSTRAINT fk_est_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ADULTO_MAYOR (
    ID_USUARIO     INT NOT NULL,
    EDAD           INT,
    USUARIO_CORRIENTE TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_USUARIO),
    CONSTRAINT fk_aa_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE TARJETA (
    ID_TARJETA    INT            NOT NULL AUTO_INCREMENT,
    SALDO         DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
    ESTADO        VARCHAR(20)    NOT NULL DEFAULT 'ACTIVA',
    LIMITE_DIARIO DECIMAL(10,2),
    ID_USUARIO    INT            NOT NULL,
    PRIMARY KEY (ID_TARJETA),
    CONSTRAINT fk_tar_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

ALTER TABLE RECARGA
    ADD COLUMN ID_TARJETA INT NOT NULL,
    ADD CONSTRAINT fk_rec_tarjeta FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA);

CREATE TABLE AUTOBUS (
    ID_AUTOBUS        INT          NOT NULL AUTO_INCREMENT,
    RUTA_LINEA        VARCHAR(50)  NOT NULL,
    SOAT              VARCHAR(50),
    REVISION_TECNICA  VARCHAR(50),
    PRIMARY KEY (ID_AUTOBUS)
);

CREATE TABLE LECTOR_DE_TARJETA (
    ID_LECTOR  INT NOT NULL AUTO_INCREMENT,
    ID_AUTOBUS INT NOT NULL,
    PRIMARY KEY (ID_LECTOR),
    CONSTRAINT fk_lec_bus FOREIGN KEY (ID_AUTOBUS) REFERENCES AUTOBUS(ID_AUTOBUS)
);

CREATE TABLE CHOFER (
    CI_CHOFER           VARCHAR(20)  NOT NULL,
    ID_INTERNO          VARCHAR(20),
    NOMBRE              VARCHAR(100) NOT NULL,
    NUMERO              VARCHAR(20),
    DIRECCION           VARCHAR(200),
    LICENCIA_DE_CONDUCIR VARCHAR(50),
    PRIMARY KEY (CI_CHOFER)
);

CREATE TABLE MANEJA (
    CI_CHOFER   VARCHAR(20) NOT NULL,
    ID_AUTOBUS  INT         NOT NULL,
    FECHA_TURNO DATE        NOT NULL,
    PRIMARY KEY (CI_CHOFER, ID_AUTOBUS, FECHA_TURNO),
    CONSTRAINT fk_man_chofer FOREIGN KEY (CI_CHOFER)  REFERENCES CHOFER(CI_CHOFER),
    CONSTRAINT fk_man_bus    FOREIGN KEY (ID_AUTOBUS) REFERENCES AUTOBUS(ID_AUTOBUS)
);

CREATE TABLE VALIDACION (
    ID_COBRO       INT            NOT NULL AUTO_INCREMENT,
    ID_TARJETA     INT            NOT NULL,
    ID_LECTOR      INT            NOT NULL,
    FECHA          DATE           NOT NULL,
    HORA           TIME           NOT NULL,
    MONTO_COBRADO  DECIMAL(10,2)  NOT NULL,
    PRIMARY KEY (ID_COBRO),
    CONSTRAINT fk_val_tarjeta FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA),
    CONSTRAINT fk_val_lector  FOREIGN KEY (ID_LECTOR)  REFERENCES LECTOR_DE_TARJETA(ID_LECTOR)
);

CREATE TABLE REALIZA_SERVICIO (
    ID_CANAL    INT  NOT NULL,
    ID_SERVICIO INT  NOT NULL,
    HORA        TIME,
    FECHA       DATE,
    PRIMARY KEY (ID_CANAL, ID_SERVICIO),
    CONSTRAINT fk_rs_canal    FOREIGN KEY (ID_CANAL)    REFERENCES CANAL(ID_CANAL),
    CONSTRAINT fk_rs_servicio FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);
-- pruebasssss
INSERT INTO SERVICIO (TIPO_S, BLOQUEO_DE_T) VALUES
  ('Bus Troncal',   0),
  ('Bus Alimentador', 0),
  ('Teleférico',    0);

INSERT INTO CANAL () VALUES (), (), ();

INSERT INTO PUNTO_AUTORIZADO (DIRECCION, ID_CANAL) VALUES
  ('Av. Camacho 123, La Paz', 1);


INSERT INTO APLICACION_OFICIAL (ID_CANAL) VALUES (2);


INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO, NUMERO_TEL, DIRECCION) VALUES
  ('Ana Mamani',  SHA2('1234',256), 'ana@mail.com',   '70011001', 'Calle 1 La Paz'),
  ('Carlos Quispe', SHA2('abcd',256), 'carlos@mail.com','70022002', 'Calle 2 El Alto');

INSERT INTO ESTUDIANTE (ID_USUARIO) VALUES (1);

INSERT INTO ADULTO_MAYOR (ID_USUARIO, EDAD, USUARIO_CORRIENTE) VALUES (2, 65, 0);

-- Tarjetas
INSERT INTO TARJETA (SALDO, ESTADO, LIMITE_DIARIO, ID_USUARIO) VALUES
  (50.00, 'ACTIVA', 20.00, 1),
  (30.00, 'ACTIVA', 15.00, 2);

-- Recargas
INSERT INTO RECARGA (MONTO, TIPO_DE_PAGO, ID_CANAL, ID_TARJETA) VALUES
  (20.00, 'EFECTIVO', 1, 1),
  (15.00, 'QR',       2, 2);

-- Autobuses
INSERT INTO AUTOBUS (RUTA_LINEA, SOAT, REVISION_TECNICA) VALUES
  ('Linea 1 - Centro',  'SOAT-001', 'RT-2025-01'),
  ('Linea 2 - El Alto', 'SOAT-002', 'RT-2025-02');

-- Lectores
INSERT INTO LECTOR_DE_TARJETA (ID_AUTOBUS) VALUES (1), (2);

-- Choferes
INSERT INTO CHOFER (CI_CHOFER, ID_INTERNO, NOMBRE, NUMERO, DIRECCION, LICENCIA_DE_CONDUCIR) VALUES
  ('1234567', 'INT-01', 'Pedro Flores', '71234567', 'La Paz', 'LIC-A-001'),
  ('7654321', 'INT-02', 'Maria Lopez',  '79876543', 'El Alto', 'LIC-A-002');

-- Turnos
INSERT INTO MANEJA VALUES
  ('1234567', 1, '2025-05-28'),
  ('7654321', 2, '2025-05-28');

-- Validaciones (cobros)
INSERT INTO VALIDACION (ID_TARJETA, ID_LECTOR, FECHA, HORA, MONTO_COBRADO) VALUES
  (1, 1, '2025-05-28', '07:30:00', 2.50),
  (2, 2, '2025-05-28', '08:15:00', 2.50);

-- Realiza servicio
INSERT INTO REALIZA_SERVICIO VALUES
  (1, 1, '08:00:00', '2025-05-28'),
  (2, 2, '09:00:00', '2025-05-28');